version: 2.1

jobs:
   test1: 
      docker:
        - image: cimg/python:3.6.4 
      steps:
       - checkout
       - run: date
       


workflows:
    testdeploy1:
       jobs:
          - test1
