version: 2.1

jobs:
   test1: 
      docker:
        - image: circleci/python:3.6.4
      steps:
       - checkout
       - run: date
       - run: python3 hello.py
       - run: ls
       
       
       

workflows:
   version: 2
   testdeploy1:
       triggers: #use the triggers key to indicate a scheduled build
         #- schedule:
             #cron: "* * * * *" # use cron syntax to set the schedule
          #   filters:
           #    branches:
            #      only:
             #        - main
       jobs:
          - test1
    
       



