version: 2.1

jobs:
   test1: 
      docker:
        - image: cimg/node:17.2.0 
      steps:
       - checkout
       - run: date
       
       

workflows:
    testdeploy1:
       jobs:
          - test1
