version: 2.1

jobs:
   test1: 
      docker:
        - image: circleci/python:3.6.4
      steps:
       - checkout
       - run: date
       - run: python3 hello.py
       - run: python3 hi.py
       
       
       

workflows:
    testdeploy1:
       jobs:
          - test1
