version:2.1


jobs:
  test1:
    docker:
    - image: circleci/python:3.6.4 
    steps:
    - checkout
    - run:
        name: run test
        cmd: date
 workflows:
  testdeploy1:
    jobs:
      - test1
